# Generated by Django 3.2.6 on 2022-10-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('event_on_date', models.DateField()),
                ('event_on_time', models.TimeField()),
                ('about_event', models.TextField()),
                ('tags', models.CharField(max_length=250)),
            ],
        ),
    ]
