# Generated by Django 3.2.6 on 2022-10-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='additional_info',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='img_url',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
