# Generated by Django 3.2.6 on 2022-10-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_auto_20221027_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='img_url',
        ),
    ]
